### ISSUE TITLE
[4.0] Install from Web missing extensions

### ISSUE THREAD

**Issue by brianteeman** [joomla/install-from-web-server#58] opened 2021-03-16 17:26 UTC
I don't know if this is a JED team issue, a Install from Web plugin issue or what but The install from web plugin is only displaying extensions that are marked as compatible with **joomla 4 alpha**. It is not including extensions that are marked as compatible with **Joomla 4 Beta**

To make it even harder to find extensions you will also see that extension on JED are shown with a **4Alpha** tag on search views and then (where appropriate) a **4beta** tag on the individual item view.

So I suspect that there are multiple bugs here

**Comment by zero-24** [comment] 2021-03-26 21:22
This issue has been moved to the webinstaller server repo on request by @Llewellynvdm

**Comment by brianteeman** [comment] 2021-03-26 21:32
Shame no one actually reads

**Comment by Llewellynvdm** [comment] 2021-03-26 21:48
The current JED3 is not being further developed, as it is going to be replaced with [JED4](https://github.com/joomla/com_jed4) which by design is already solving these issues. 

So the rest of the issue is related to this repository/extension that is used to populate the web-install, and seems like the best place to have this conversation.

**Comment by brianteeman** [comment] 2021-03-26 21:52
so you are happy that joomla 4 will be released while the jed is broken?

**Comment by Llewellynvdm** [comment] 2021-03-26 22:19
Happy? who can be happy about that...

The JED is only going to get fixed with Joomla 4 and the JED4 extension that runs on native on Joomla 4 until then we are patching a sinking ship that was build and implemented long before my time in the JED.

The fact that we moved the issue here, is me saying I want to look at this and fix what we can in the current system as much as we can.

Where the JED is now and why, is clearly understood by the JED Team, and they are doing all they can to be ready for Joomla 4.

**Closed** 2021-09-21 15:45 UTC
